spatie/image

src/ManipulationSequence.php, tests/ManipulationSequenceTest.php
When iterating over a ManipulationSequence instance (which happens at [here](https://github.com/spatie/image/blob/master/src/GlideConversion.php#L40) for example), one iterates the "raw" groups array of ManipulationSequence. If this array has been merged, which always happens [here](https://github.com/spatie/image/blob/master/src/Image.php#L67) because [`Image` sets $this->manipulations to a new instance of `Manipulations`](https://github.com/spatie/image/blob/master/src/Image.php#L34) , an empty group is yielded. 
This causes `GlideConversion::performManipulations` to run a manipulation that makes no sense. I guess this was not noticed earlier because the tests nicely use `ManipulationSequence::toArray` and Glide does not trigger an error when it's called without any manipulation …
=> Fixes possible empty manipulation groups while iterating over a ManipulationSequence instance

src/GlideConversion.php
The Glide cache folder (`sys_get_temp_dir()` is used for this project by default) gets bloated with manipulation result directories; as this is the default behaviour of Glide (see http://glide.thephpleague.com/1.0/config/source-and-cache/). 
When manipulating lots of images, `sys_get_temp_dir()` gets clogged with folders and (in our case) touching the limits of filesystems (number of inodes allocated). We are getting random "No free space left on device" errors because of this.
This patch deletes the directory Glide created after saving the manipulated image.
=> Clean up Glide cache directory after saving manipulated image

src/GlideConversion.php
`rename()` will produce warnings and `GlideConversion` will throw an `ErrorException` if it is used across different volumes/disks so a simpler solution would be to break it in two parts using `copy()` and `unlink()`.
This is the cause behind https://github.com/spatie/laravel-medialibrary/issues/588 but changing PHP's `tmp` directory may not always be possible (or convenient), so this is why I'm submitting this PR.
=> Use copy() & unlink() instead of rename()

src/Manipulations.php, tests/ManipulationsTest.php
WIth this fix you can send a normal manipulation:
```php
$media->manipulations = [
'resized' =>['width' => 123, 'height' => 123],
];
```
And also this kind of manipulations:
```php
$resizedConversion = Manipulations::create()
->width(123)
->apply()
->manualCrop(20, 20, 10, 10);
$media->manipulations = [
'resized' => $resizedConversion->toArray()
];
```
=> Update Manipulations.php to let manipulations arrays also

README.md
Add a note in the installation section that highlights that the package requires PHP exif extension since version 1.5.3
=> Update Readme - Include exif Requirement

src/Image.php
Temporary directory setting is now after GlideConversion creation and before image manipulations, so that setting a custom temporary directory on an Image object (via Image->setTemporaryDirectory()) has the expected effect.
=> Change GlideConversion sequence

composer.json, src/Manipulations.php
`strtoupper('fit')` returns `FİT` when language set to Turkish.
`$this->addMediaConversion('test')->fit(Manipulations::FIT_CROP, 64,64)->performOnCollections('test')` throwing InvalidManipulation all the time.
`mb_strtoupper('fit')` workings corrects and returns `FIT`.
Fixes #98
=> change uppercase function to mb_strtoupper instead of strtoupper

docs/image-manipulations/resizing-images.md
example-fit-stretch.jpg is a 450x150 stretched jpg. Updated example code to reflect that.
=> Updates docs to show correct example

composer.json, docs/image-manipulations/optimizing-images.md, src/Image.php, tests/Manipulations/OptimizeTest.php
After some thinking about #106, not only `binaryPath` could be customized. 
`OptimizerChain` also has some others options such as `setTimeout` so one should be able to pass a custom `OptimizerChain`. 
`performOptimization` is reusing/updating existing `BaseOptimizer` instances, if they exist, instead of creating new ones.
=> Allow usage of a custom `OptimizerChain` (#106)

src/GlideConversion.php
This prevents the method from deleting the temp folder in some cases.
Maybe deleting the whole condition is an option too?
More: #117
=> change condition to delete $conversionResultDirectory

.gitignore, src/Image.php, src/Manipulations.php, tests/ImageTest.php
supporting from avif format is requested long time ago: in https://github.com/spatie/image/issues/137 and https://github.com/spatie/image/issues/92 in one of my project i really want to use avif format with https://github.com/spatie/laravel-medialibrary so i created this PR to add this format to the supported format list.
libgd started to support avif from version 2.3.2 using libavif 
and according to this blog post it will be available to the php users since php 8.1 [PHP 8.1: GD: AVIF image support](https://php.watch/versions/8.1/gd-avif)
imagemagick start supporting from avif format using libheif since version 7.0.25 
i've added test for both gd and imagick driver but i only test imagick with ImageMagick version  7.1.0-12 Q16-HDRI x86_64 2021-10-24
=> add avif support

docs/image-manipulations/resizing-images.md
Great work guys, I appreciate your packages!
I was confused by the docs the same as issue #136 and found the glide docs descriptions which appeared to be helpful. This change is just to lift those descriptions directly into these docs.
I think this resolves #136 where it removes the 'FIT_FILL' is like 'FIT_CONTAIN' and just uses a basic description to describe the behaviour. The rest of the change is just for consistency.
Feel free to request any changes 😃 
Cheers,
=> [REF] updated fit docs description

composer.json
As mentioned in #151 it seems to work well also with `symfony/process` in version `6.0`.
=> Adding compatibility to Symfony 6

composer.json, docs/usage/saving-images.md, src/Image.php, src/Manipulations.php, tests/ImageTest.php
Now that [Glide's TIFF support is fixed](https://github.com/thephpleague/glide/releases/tag/2.2.2), I can submit this PR to support [the discussion in Media Library](https://github.com/spatie/laravel-medialibrary/discussions/2794)!
=> Add TIFF support

src/GlideConversion.php
This pull request fixes an exception that i got on a shared webspace (where I'm not able to read the contents of the `/tmp` directory):
```
Failed to open directory: Permission denied at [...]/vendor/spatie/image/src/GlideConversion.php:185
```
=> Fix permission issue with temporary directory

src/Manipulations.php
Problem: 
As some images have an EXIF orientation, I had the problem with rotating an image to its default orientation without EXIF. I just needed the EXIF orientation data to be ignored/deleted.
Solution:
Glide supports zero orientation to rotate an image in the same orientation as before but ignoring the EXIF orientation.
This PR adds the possibility to rotate an image by zero, deleting EXIF orientation.
=> Add zero orientation support ignoring EXIF

src/Manipulations.php, tests/Manipulations/FitTest.php
Currently the `fit()` manipulation requires you to specify both a width and a height. But in my projects, I only want to fit the image within a specific width. The height does not matter. This PR makes it possible to use the `fit()` with only a height or width by using named arguments.
```php
$image->fit(Manipulations::FIT_MAX, width: 500);
$image->fit(Manipulations::FIT_MAX, height: 500);
```
=> Fit with only width or height

docs/image-manipulations/optimizing-images.md, tests/Manipulations/OptimizeTest.php
This PR adds documentation on how to set the timeout for image optimizations other than the default 60 seconds.
It was previously implemented in the https://github.com/spatie/image/pull/187, but after the new major v3 release the way we can configure image optimizations changed.
=> Add `OptimizerChain::setTimeout()` to the image optimization tests and docs

src/Image.php, tests/ImageTest.php
Reference: https://twitter.com/freekmurze/status/1736801633986916639
When passing an image filename to `Image::__construct()` and `Image::load()`, the file wasn't actually being loaded by the driver. The only way for it to work would be `(new Image())->loadFile('file/path')`.
=> Image load fix

phpstan-baseline.neon, src/Drivers/Gd/GdDriver.php, tests/ImageFormatTest.php
related: https://github.com/spatie/laravel-medialibrary/pull/3474
=> update GD driver

docs/usage/basic-usage.md
The `ImageDriver` enum has `Gd` as case instead of `GD`.
=> Fix enum case

docs/usage/basic-usage.md
The `load` method creates a new class from `static` and ignores the changed image drive. I guess in this example, the `loadFile` method should be used.
=> update load image with gd driver example

src/Drivers/Gd/GdDriver.php, src/Image.php
in PHP8.1 a new [IMG_WEBP_LOSSLESS](https://www.php.net/manual/en/image.constants.php#constant.img-webp-lossless) constant has been added to allow lossless conversion for webp
this PR will extend the quality allowed range from 0-100 to 0-101 (IMG_WEBP_LOSSLESS value)
=> [fix] Allow constant IMG_WEBP_LOSSLESS in quality

src/Drivers/Gd/GdDriver.php
In a similar vein to #243, this update silences exif data warnings. 
When importing thousands of images, a small percentage created exif warnings and therefore were unable to be processed, leaving gaps in our catalog data.
I would presume the majority would prefer image conversions to continue, rather than error.
=> Suppress warnings from exif_read_data

src/Drivers/Gd/GdDriver.php
`imagecreatefromstring` handles warnings as errors, and throws exceptions that wouldn't impact image manipulation.
For example:
`ErrorException: imagecreatefromstring(): gd-png: libpng warning: iCCP: known incorrect sRGB profile`
This is a warning, and image manipulations work fine when the warning is ignored.
This pull request suppresses those warnings so they don't cause manipulations to fail unnecessarily.
=> Suppress warnings from imagecreatefromstring

src/Drivers/Gd/GdDriver.php, src/Drivers/ImageDriver.php, src/Drivers/Imagick/ImagickDriver.php, src/Image.php
Before:
```php
public function registerMediaConversions(BaseMedia $media = null): void
{
$this->addMediaConversion('avatar-minified')
// It's not possible to define a background color.
->fit(Fit::Fill, 320, 320)
->performOnCollections('avatar');
}
```
```php
public function registerMediaConversions(BaseMedia $media = null): void
{
$this->addMediaConversion('avatar-minified')
// We can now specify the background color we want
->fit(Fit::Fill, 320, 320, false, $media?->custom_properties['background'] ?? '000000')
->performOnCollections('avatar');
}
```
Before:
After:
=> Ability to resize canvas when keeping fill background a certain color

src/Drivers/Imagick/ImagickDriver.php, tests/Manipulations/BlurTest.php, tests/Manipulations/PixelateTest.php, tests/Manipulations/SharpenTest.php
Because pull request #262 was a complete mess, here another one.
Fixing a bug in ImagickDriver::pixelate causing a DivisionByZeroError.
=> Fix bug in ImagickDriver::pixelate, Update tests

src/Drivers/Gd/GdDriver.php, tests/Manipulations/ResizeTest.php
Should resolve [this issue](https://github.com/spatie/laravel-medialibrary/issues/3502) with GdDriver `fit` and `resizeCanvas`.
=> fix: GdDriver resizeCanvas save alpha channel;

docs/usage/basic-usage.md
The docs point to an old version of the link, and it's broken.
=> Fix broken link

src/Drivers/Gd/GdDriver.php
Why: some of these functions are optional and can be not available in the installed PHP. When PHP couldn't find functions in the current and root namespaces, it reports a missing function in the current namespace. As a result, an Error message is misleading.
Example: `Call to undefined function Spatie\Image\Drivers\Gd\imageavif()`
With this small fix, the error message will be:
```
Call to undefined function imageavif()
```
=> Improve DX by specifying namespace for GD functions

docs/image-manipulations/resizing-images.md
I found out small mistake in documentation.
=> Correct documentation for FillMax in resizing-images.md

docs/usage/basic-usage.md
- using the previous command
```php
Image::useImageDriver(ImageDriver::Gd)->loadFile(string $pathToImage);
```
gave me following errors 
1. Non static method 'useImageDriver' should not be called statically.
2. Undefined method 'loadFile'
3. undefinedType ImageDriver
- The correct command is as follows:
```php
Image::load($file)->useImageDriver('imagick')
```
=> Correction: Update basic-usage.md Selecting a driver" section

src/Drivers/Imagick/ImagickDriver.php
I noticed resizing images using `fit()` will sometimes change the look of the image. But not for all images, and not for every `Fit::` value. The problem seems to be in `resizeCanvas()`: color profiles will not transfer over to the new canvas.
This PR makes sure that the IMagick driver will copy the color profiles to the new instance that is made in `resizeCanvas()`. I have no fix for the GD driver, as [GD currently does not support color profiles](https://github.com/libgd/libgd/issues/136).
=> Do not remove color profiles when resizing canvas.

src/Enums/Orientation.php
Hey, I am not so familiar with the package, but when using the orientation chained method, I cannot pass a degree other than 0, 90, 180 and 270 since the argument is type hinted to the enum Spatie\Image\Enums\Oritentation, so I thought adding a new case RotationMinus90 would be a good idea.
`Image::load($media->getPath())->orientation($request->get('direction') === 'left' ? -90 : Orientation::Rotate90)->base64();`
=> Add -90 rotation degree

src/Size.php
- Added early returns for invalid width and height inputs
- Ensured that invalid width or height throws appropriate exceptions before resizing
- Simplified logic for resizing dominant width and height
=> refactor: simplify resize method
