- README.md
Tried to play with the package, then I got the error that `rotate` doesn't seem to exist in Manipulations. `orientation` did work, so this would probably be a better example. I may be overlooking something though 😄
> Fix call to rotate in readme

- src/GlideConversion.php
> Revert "Clean up Glide cache directory after saving manipulated image"

- src/GlideConversion.php
> Remove temporary directory after using it (if it's empty)

- CHANGELOG.md
- composer.json
- src/Image.php
- tests/ImageTest.php
This PR adds an optimize method. Optimization leverages [psliwa/image-optimizer](https://github.com/psliwa/image-optimizer).
> Add optimize method

- src/GlideConversion.php
This is a fix for [#132 in spatie/browsershot](https://github.com/spatie/browsershot/issues/132)
> Don't use folders in cache path

- .styleci.yml
- CHANGELOG.md
- src/GlideConversion.php
- src/ManipulationSequence.php
- src/Manipulations.php
- tests/Manipulations/FlipTest.php
> Add is_writeable check before deleting a directory

- src/Manipulations.php
> fix invalid height exception

- src/Manipulations.php
All other code appears to be in place, but not having the const will throw an error on when generating appropriate WebP files.
> Updating manipulations with webp format.

- src/Image.php
- tests/ImageTest.php
Related to: https://github.com/spatie/docs.spatie.be/pull/417
> Add support and tests for webp and pjpg.

- composer.json
- docs/image-manipulations/optimizing-images.md
- src/Image.php
- tests/Manipulations/OptimizeTest.php
> Revert "Allow usage of a custom `OptimizerChain` (#106)"

- composer.json
- docs/image-manipulations/optimizing-images.md
- src/Image.php
- tests/Manipulations/OptimizeTest.php
Sorry, I forgot that `array_filter` preserves indexes. This is now fixed.
> Allow usage of a custom `OptimizerChain` (#106)

- docs/image-manipulations/optimizing-images.md
Just noticed docs contained a mistake. This PR fixes this.
> Fix custom OptimizerChain docs

- src/GlideConversion.php
In this PR, I try to convert into match expressions that makes code easier to read.
> Use match expression in convertToGlideParameter method 

- .github/workflows/php-cs-fixer.yml
- .github/workflows/run-tests.yml
- .gitignore
- .php_cs.dist.php
- composer.json
- add support for Symfony 6
- run test suite with php 8.1
> Add support for Symfony 6

- README.md
- docs/image-manipulations/resizing-images.md
- src/Manipulations.php
It has been added in glide v2.0
https://glide.thephpleague.com/2.0/api/size/
> Add fill-max fit mode

- src/Manipulations.php
```php
// before
$image->removeManipulation('blur');
$image->save($path);
// after
$image->removeManipulation('blur')->save($path);
```
> Return self on `remove Manipulation` for concatenation

- .github/workflows/phpstan.yml
- composer.json
- phpstan-baseline.neon
- phpstan.neon.dist
- src/Drivers/Color.php
- src/Drivers/Concerns/CalculatesCropOffsets.php
- src/Drivers/Concerns/CalculatesFocalCropCoordinates.php
- src/Drivers/Concerns/GetsOrientationFromExif.php
- src/Drivers/Gd/GdColor.php
- src/Drivers/Gd/GdDriver.php
- src/Drivers/ImageDriver.php
- src/Drivers/Imagick/ImagickColor.php
- src/Drivers/Imagick/ImagickDriver.php
- src/Enums/CropPosition.php
- src/Enums/Fit.php
- src/Exceptions/InvalidManipulation.php
- src/Exceptions/UnsupportedImageFormat.php
- src/Size.php
The 7 failing tests are the same as the one from the v3, so not related to this PR
- in Fit.php line 30 I added a todo comment
- Verify if all added int and/or float types are correct
> Add PHPstan

- docs/upgrading.md
Move upgrade docs into docs section so they build on the docs website.
Also duplicates and closes #212
> Update and rename UPGRADING.md to docs/upgrading.md

- composer.json
https://github.com/spatie/image/pull/215#issuecomment-1868023970
> move ext requirement to dev

- src/Enums/Orientation.php
- src/Enums/Unit.php
Adds ability to store and recreate these enums. Primary for using with laravel-medialibrary
> Convert Unit and Orientation to BackedEnum

- docs/usage/basic-usage.md
The changes I suggested was for v2 branch not for the main branch sorry. Reverting back the changes
> Update basic-usage.md Reverting back the incorrect changes that I suggested

- src/Size.php
- Restructure logic with early return for invalid width
- Extract constraint checks to variables for clarity
- Simplify aspect ratio preservation and DoNotUpsize logic
> refactor: simplify resizeWidth method

- src/Size.php
- Reorganize logic with early return for invalid height
- Extract constraint checks to variables for better readability
- Reduce nested conditions by calculating new dimensions upfront
- Maintain existing behavior for DoNotUpsize and PreserveAspectRatio
> refactor: simplify and optimize resizeHeight method

- src/Drivers/Gd/GdDriver.php
Replaces manual file handling with file_get_contents for improved readability and safety. Adds is_file() and filesize() checks to prevent unnecessary or invalid reads
> refactor: simplify loadFile by replacing fopen/fread with file_get_contents
